# Commands for joining the server
join commands:
  # The id for this command is "exampleCommand1"
  # There is no use for this right now so you can set it to anything
  # Just make sure none of them are the same
  exampleCommand1:
    # The command to run
    # Do not put a /
    # You can run it as the player if you add [PLAYER] to the beggining
    # You can run it as the player with all permissions if you add [OP] to the beginning
    # You can run it as a bungee player if you add [PBUNGEE] to the beginning (and if JoinCommandsBungee is installed on your BungeeCord Proxy)
    # You can run it as the bungee console if you add [CBUNGEE] to the beginning (and if JoinCommandsBungee is installed on your BungeeCord Proxy)
    #
    # Valid Placeholders:
    # - {player}: The name of the player that joined
    command: 'msg {player} Welcome to the server!'
    
    # How long to wait after the player has joined
    # This is in ticks, so 20 = 1 second
    delay: 20
    
    # Should this commmand require a permission to execute?
    # Set this to '' to not use a permission
    permission: ''
    
    # Should this command only execute the first time a player joins?
    # Set this to false to execute on every join
    first join only: true
    
  #exampleCommand2:
  #  command: '[PLAYER]suicide'
  #  delay: 40
  #  permission: 'jc.we.hate.you'
  #  first join only: false
  
  #examplecommand3;
  #  command: '[PBUNGEE]server factions'
  #  delay: 10
  #  permission 'server.auto.join.factions'
  #  first join only: false
  
# Commands for joining worlds
world join commands:
  # The id for this command is 'exampleCommand4'
  # There are no uses for command ids right now so you can set it to anything
  # Just make sure none of them are the same
  exampleCommand4:
    # A list of worlds to run this command in  
    # If your worlds are named by numbers, please place "" around them
    # Example: "1"
    worlds:
    - "world"
    - "1"
    
     
    # The command to run
    # Do not put a /
    # You can run it as the player if you add [PLAYER] to the beggining
    # You can run it as the player with all permissions if you add [OP] to the beginning
    # You can run it as a bungee player if you add [PBUNGEE] to the beginning (and if JoinCommandsBungee is installed on your BungeeCord Proxy)
    # You can run it as the bungee console if you add [CBUNGEE] to the beginning (and if JoinCommandsBungee is installed on your BungeeCord Proxy)
    #
    # Valid Placeholders:
    # - {player}: The name of the player that joined
    # - {world_name}: The name of the world that the player is in
    command: "msg {player} Welcome to {world_name}"
    
    # How long to wait after the player has been teleported to one of these worlds.
    # This is in ticks, so 20 = 1 second
    delay: 20
    
    # Should this commmand require a permission to execute?
    # Set this to '' to not use a permission
    permission: 'joincommands.welcome.worlds'
    
    # Should this command only execute the first time a player telports to these worlds?
    # Set this to false to execute on every teleport to these worlds
    first join only: true